- type: entity
  id: TinyFanCircuitboard
  parent: BaseMachineCircuitboard
  name: tiny fan machine board
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: AtmosDeviceFanTiny
      stackRequirements:
        Manipulator: 2
        CableHV: 5
        Uranium: 2
        Gold: 10

- type: entity
  id: TinyFanDirectionalCircuitboard
  parent: BaseMachineCircuitboard
  name: directional tiny fan machine board
  components:
    - type: Sprite
      state: engineering
    - type: MachineBoard
      prototype: AtmosDeviceFanDirectional
      stackRequirements:
        Manipulator: 2
        CableHV: 5
        Uranium: 5
        Gold: 10
