- type: playTimeTracker
  id: JobCentralCommandBlueShieldOfficer

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobSecurityPilot
